[build]
publish = "qdrant-landing/public"
command = "bash -x ./install-and-build.sh"

[build.environment]
HUGO_VERSION = "0.123.0"
DART_SASS_VERSION = "1.70.0"
NODE_VERSION = "20.10.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
DEPLOY_PRIME_URL = "https://qdrant.tech"

[context.deploy-preview.environment]
HUGO_ENV = "staging"

[[headers]]
    for = "/*"
    [headers.values]
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"

[[headers]]
    for = "/*.css"
    [headers.values]
        X-Frame-Options = ""

[[headers]]
    for = "/*.js"
    [headers.values]
        X-Frame-Options = ""

[[headers]]
    for = "/*.svg"
    [headers.values]
        X-Frame-Options = ""

[[headers]]
    for = "/*.png"
    [headers.values]
        X-Frame-Options = ""

[[headers]]
    for = "/*.jpeg"
    [headers.values]
        X-Frame-Options = ""

[[headers]]
    for = "/*.webp"
    [headers.values]
        X-Frame-Options = ""

[[headers]]
    for = "/*.woff2"
    [headers.values]
        X-Frame-Options = ""

[[headers]]
    for = "/*.webmanifest"
    [headers.values]
        X-Frame-Options = ""

[[redirects]]
    from = "/surveys/hybrid-saas"
    to = "https://hybrid-cloud.qdrant.tech/"
    status = 301
    force = true

[[redirects]]
    from = "/surveys/hybrid-saas/"
    to = "https://hybrid-cloud.qdrant.tech/"
    status = 301
    force = true
